WIDTH, HEIGHT = 1280, 720
N = 500
DAMPING = 0.999 # coefficient de frottement : 0.999
K = 0.3 # "largeur de la vague" base : 0.4
MAX_FORCE_APPLIED = 1 # nombre de force appliqué lorsque la balle touche la vague
RESORTING_FORCE = 0.005 # "force de retour" base : 0.005
PROPAGATION_RANGE = 5 # portée de la vague base : 3
PROPAGATION_WEIGHTS = [0.7, 0.5, 0.3, 0.2, 0.1] # poids de la propagation base : [0.5, 0.3, 0.2]
BOAT_IMAGE_PATH = "assets/boat.png"
BOAT_SPEED = 5
WAVE_BASE_HEIGHT = HEIGHT // 2
ALPHA = 0.5 # coefficient de non-linéarité base : 0.5
SIMULATION_STEPS = 1 # nombre de mise à jour de la vague par itération
